#Assignment 3 - 
1.Write a function to compute 5/0 and use try/except to catch the exceptions. 

In [7]:
#Define a function which divides two numbers and prints the exceptions.
def divisionoftwo(a,b):
    try :
        c = a/b
    except Exception as e : 
        print("Exception is :- ",e)
    else :
        print("divide executed correctly",c)

print(divisionoftwo(5,0))
#output is as below.

Exception is  division by zero
None


2. Implement a Python program to generate all sentences where subject is in ["Americans", "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"]. 
Hint: Subject,Verb and Object should be declared in the program as shown below. 
subjects=["Americans ","Indians"] verbs=["play","watch"] objects=["Baseball","Cricket"] 
Output should come as below: 
Americans  play Baseball.
Americans  play Cricket. 
Americans  watch Baseball. 
Americans  watch Cricket. 
Indians play Baseball. 
Indians play Cricket. 
Indians watch Baseball. 
Indians watch Cricket. 

In [20]:
subjects=["Americans","Indians"] 
verbs=["play","watch"] 
objects=["Baseball","Cricket"] 
#put in loop of all three lists so that the required is printed.
for i in subjects :
    for j in verbs :
        for k in objects :
            print(i,j,k)
#output is as below.

Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


1.Write a function so that the columns of the output matrix are powers of the input vector.  The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.  
 
HINT: Such a matrix with a geometric progression in each row is named for Alexandre Theophile Vandermonde. 

Answer 1 :- Using Numpy

In [2]:
import numpy
x = numpy.array([1,2,3,5])
N = 3
print(numpy.column_stack([x**(N-1-i) for i in range(N)]))
#Output is as below.

[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [25  5  1]]


Answer 2 :- Using python Core code (this is without using NUmpy and above using NUmpy)

In [23]:
def printGP(a, r, n):  
    for i in range(0, n):  
        curr_term = a * pow(r, i) 
        print(curr_term, end =" ") 
# Driver code  
a = 2 # starting number 
r = 3 # Common ratio 
n = 5 # N th term to be find 
printGP(1, 2, 5) 

1 2 4 8 16 

In [33]:
Y = 7
i = 5
listgp = [a**(Y-1-i) for i in range(Y)]
print(listgp)

[64, 32, 16, 8, 4, 2, 1]
